const data = {
  products: [
    {
      _id: '1',
      productName: 'venta',
      category: 'uno',
      image: '/images/p1.jpg',
      price: 123,
      brand: 'niky',
      raiting: 4.5,
      numbReview: 10,
      description: 'high cuality producto',
    },
    {
      _id: '2',
      productName: 'lacoste',
      category: 'dos',
      image: '/images/p2.jpg',
      price: 45,
      brand: 'lacoste',
      raiting: 4,
      numbReview: 8,
      description: 'high cuality producto',
    },
    {
      _id: '3',
      productName: 'alcantarilla',
      category: 'uno',
      image: '/images/p3.jpg',
      price: 67,
      brand: 'lacoste',
      raiting: 4.9,
      numbReview: 100,
      description: 'high cuality producto',
    },
    {
      _id: '4',
      productName: 'sombrilla',
      category: 'dos',
      image: '/images/p4.jpg',
      price: 5,
      brand: 'amarilla',
      raiting: 5,
      numbReview: 7,
      description: 'high cuality producto',
    },
    {
      _id: '5',
      productName: 'laptop',
      category: 'electronics',
      image: '/images/p5.jpg',
      price: 400,
      brand: 'hp',
      raiting: 4.5,
      numbReview: 4,
      description: 'high cuality producto',
    },
    {
      _id: '6',
      productName: 'mouse',
      category: 'electronics',
      image: '/images/p1.jpg',
      price: 8,
      brand: 'logitec',
      raiting: 2.3,
      numbReview: 10,
      description: 'high cuality producto',
    },
  ],
}

export default data
// :
